### ISSUE TITLE
Is there some plan with java api. 

### ISSUE THREAD

**Issue by huhu-sky** [karmada-io/api#11]
use https://github.com/fabric8io/kubernetes-client  to  extend java api. or official client to extend.

**Comment by RainbowMango** [comment]
I'm not familiar with the `fabric8io/kubernetes-client`, does it helps to build the JAVA client SDK for Karmada?

**Comment by liangyuanpeng** [comment]
@huhu-sky  You can try to generate java code with https://github.com/kubernetes-client/java

Some doc:  
- https://github.com/kubernetes-client/java/wiki/5.-Generate-Java-CRD-Model

**Comment by RainbowMango** [comment]
@huhu-sky We don't have a plan for the Java client yet, but we are looking forward to a use case to prove that we really need it.

/close

**Comment by RainbowMango** [comment]
Thanks @liangyuanpeng for the answer, I bet it'd be helpful.
